name: pannuke
profile: hv_pannuke
id: 1.0

# 1st - extract patches
data_dir: data_hv_pannuke
extract_type: mirror
data_modes:
  - train
  - test
  - valid

# 2nd - training
input_augs: p_standard
train_dir:
- train/Annotations
valid_dir:
- valid/Annotations

# 3rd - inference
inf_auto_find_chkpt: true
inf_auto_metric: valid_dice
inf_batch_size: 16
inf_data_list:
  - data_hv_pannuke/test/Images/
